### ISSUE TITLE
 java.lang.StringIndexOutOfBoundsException on Wizard

### ISSUE THREAD

**Issue by mariolatronico** [pedromateo/tug_qt_unit_testing_fw#1]
I tried to use the wizard to generate a test for my widget. 
On step 1 I selected the .ui file (every checkbox on this step is unselected, class name is correctly parsed from the .ui file)
On step 2 I unselected the checkbox "Add controller/GW to the test project" (BTW, I don't know what it is or how can I generate, i tried to skim the manual but I found no mention on how to create it)
On step 3 and 4 I unselected the checkbox 
On step 5 everything is unselected
On step 6 I selected the checkbox
On step 7 I gave a name and a target directory ( 7.3 is unselected)

After pressing generate the wizard gives an exception
```
@Status: Retrieving generation data.
@Status: Getting and validating data for generation process.
Exception in thread "AWT-EventQueue-0" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at org.eclipse.tug.utils.FileSystemUtils.GetDirFromPath(FileSystemUtils.java:88)
	at org.eclipse.tug.wizard.WizardWindowGen.__getGenerationData(WizardWindowGen.java:434)
	at org.eclipse.tug.wizard.WizardWindowGen.but_generate__actionPerformed(WizardWindowGen.java:93)
	at org.eclipse.tug.wizard.WizardWindowWidget$37.actionPerformed(WizardWindowWidget.java:1441)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
@ERROR @Status: Parameter 'gw_lib' is empty.
@ERROR @Status: Parameter 'gw_lib' is empty.
```

**Comment by pedromateo** [comment]
Hi Mario,

in current version you have to provide all classes related to the panel within a library. BTW, this error should be detected before and generation should have been prevented. 

I am working on a new version in which you can generate a project just using a ui panel and its .h and .cpp files. However, I have not much time, so please be patient and up to date to the project.

Sorry for the inconvenience and thanks for the feedback.

**Comment by mariolatronico** [comment]
Hi Pedro,

Thank you. Is there a way I can help ?
I'm also trying to use TUG under Windows, I managed to compile it using
mingw32 (gcc 4.9.2), but since I can't use it I don't know if the binary is
correct.

**Comment by pedromateo** [comment]
Hi,

I am working on a couple of changes and in one example. I hope to finish it tomorrow. Then, before fixing these errors, it would be great if you can help trying to compile a TUG project in Windows and proposing the needed changes that should be made to the generated test projects.

Thanks.

**Comment by mariolatronico** [comment]
Ok thank you.
The compilation errors in Windows regard some signal constant that aren't
defined under mingw (SIGCONT, SIGQUIT, SIGPIPE) used in qt_TestUtils.hpp.
I'll try to inspect the code and see if I can create a patch.

**Comment by pedromateo** [comment]
I fixed some errors, created a new version and uploaded it.
I also added a very simple example, including initial project, final project, and images describing the 7 steps to reproduce the scenario.

**Comment by pedromateo** [comment]
Please, reopen this issue or open a new one if new errors arise.
Thanks so much.

**Comment by mariolatronico** [comment]
Unfortunately, I doesn't work. I followed exactly the instructions referenced by the images, but it gives the exception again.

The stacktrace is:

```
@Status: Retrieving generation data.
@Status: Getting and validating data for generation process.
Exception in thread "AWT-EventQueue-0" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at org.eclipse.tug.utils.FileSystemUtils.GetDirFromPath(FileSystemUtils.java:91)
	at org.eclipse.tug.wizard.WizardWindowGen.__getGenerationData(WizardWindowGen.java:441)
	at org.eclipse.tug.wizard.WizardWindowGen.but_generate__actionPerformed(WizardWindowGen.java:93)
	at org.eclipse.tug.wizard.WizardWindowWidget$36.actionPerformed(WizardWindowWidget.java:1427)
```
I think that the problem may lie in the path handling code; since I'm using Windows.
In 7.2 the directory in my case is : D:\code\tug_qt_unit_testing_fw\examples\password_dialog\tut_test_example

**Comment by pedromateo** [comment]
Are you using the new version?
Anyway, I think it is because I am considering always path separator as "/", which I think it will not work in Windows. This is a small change, but I need to do it tomorrow morning in the office, where I have the full development environment.

Tomorrow morning I will upload a new version.
Sorry for the inconvenience.

**Comment by mariolatronico** [comment]
I'm using version 1.8.1.
Tomorrow I will not be in office and I can't test on windows, but I can do
it on Monday. Meanwhile I can test it on OSX from home.

By the way, Is there any chance to have the sources of the Java GUI ?

**Comment by pedromateo** [comment]
I made several changes related to the path separator along the whole application. I have no windows system to test it, so it might still failing in some of the features. It would be great if you can test the new version and report me the potentials errors.

With respect to the sources, I can free them with no problem. I will discuss it with the company. However, this application is a bit complex because it is developed in Java, but the Acceleo engine is used as well to generate the Qt panel enriched with testing methods. It is a messy setup, and I dont know if it will work well in other environments.

**Comment by mariolatronico** [comment]
Ok, I will try it on monday. Meanwhile I tested the software on the OSX enviroment and it seems to work (both the GUI and the library).

The output of the test are :
```
********* Start testing of Testsuite_MainWindow_1 *********

Config: Using QtTest library 5.5.0, Qt 5.5.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 6.0 (clang-600.0.56) (Apple))

Configuring testsuite...

PASS   : Testsuite_MainWindow_1::initTestCase()

Configuring test...

QDEBUG : Testsuite_MainWindow_1::test1() Executing test 'Testsuite_MainWindow_1::test1' (panel already launched)

FAIL!  : Testsuite_MainWindow_1::test1() 'Testsuite_MainWindow_1::test1' Empty test.

   Loc: [/Users/mario/Documents/code/tug_qt_unit_testing_fw/tug_base_lib/qt_TestUtils.hpp(128)]

Finishing test...

Configuring test...

QDEBUG : Testsuite_MainWindow_1::test2() Executing test 'Testsuite_MainWindow_1::test2' (panel already launched)

FAIL!  : Testsuite_MainWindow_1::test2() 'Testsuite_MainWindow_1::test2' Empty test.

   Loc: [/Users/mario/Documents/code/tug_qt_unit_testing_fw/tug_base_lib/qt_TestUtils.hpp(128)]

Finishing test...

Finishing testsuite execution...

PASS   : Testsuite_MainWindow_1::cleanupTestCase()

Totals: 2 passed, 2 failed, 0 skipped, 0 blacklisted

********* Finished testing of Testsuite_MainWindow_1 *********
```

For the GUI I asked for the sources because, in case of errors, I'd be able to debug and possibly contribute with patches.

**Comment by mariolatronico** [comment]
No more luck :(

```

@Status: Retrieving roundtrip data.
@Status: Generating testsuite projects.
Exception in thread "AWT-EventQueue-0" java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
	at java.util.regex.Pattern.error(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.util.regex.Pattern.<init>(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.lang.String.split(Unknown Source)
	at java.lang.String.split(Unknown Source)
	at org.eclipse.tug.utils.FileSystemUtils.GetRelativePath(FileSystemUtils.java:203)
	at org.eclipse.tug.wizard.WizardWindowGen.__generateTestsuites(WizardWindowGen.java:275)
	at org.eclipse.tug.wizard.WizardWindowGen.but_generate__actionPerformed(WizardWindowGen.java:108)
	at org.eclipse.tug.wizard.WizardWindowWidget$36.actionPerformed(WizardWindowWidget.java:1433)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

I also have problems with on 5.5 ("check/edit config file" button), Clicking on the button has no results. I tried also to click on it AFTER I clicked the Generate button and, since the stderr is redirected to the panel in the windows, the error is :
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(Unknown Source)
	at org.eclipse.genericeditor.EditImplFrame.bind(EditImplFrame.java:135)
	at org.eclipse.genericeditor.menus.EditImplToolBar.<init>(EditImplToolBar.java:38)
	at org.eclipse.genericeditor.EditImplFrame.<init>(EditImplFrame.java:124)
	at org.eclipse.tug.utils.DialogsUtils.ShowFileEditor(DialogsUtils.java:16)
	at org.eclipse.tug.wizard.WizardWindowImpl.but_edit_tuglib_file__actionPerformed(WizardWindowImpl.java:610)
	at org.eclipse.tug.wizard.WizardWindowWidget$23.actionPerformed(WizardWindowWidget.java:1090)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by pedromateo** [comment]
I will try to fix it asap... maybe tomorrow morning.
BTW, I added the wizard sources to the GIT repository. The model-based part is not added yet.

**Comment by mariolatronico** [comment]
I probably found the error. I created a test case for FileSystemUtils.java and in line 198 (and equally at 199) the line 
```
new File(mybase).getCanonicalFile().toURI().getPath()
```
creates an URI with slash (/) but the split at line 203 is performed with the system file separator, which in Windows systems is the backslash (\), that can't be alone a valid regular expression. 
Changing the line 203 (and similarly the following one) to  
```
String[] basePaths = a.split("/"); 
```
seems to works, but since I can't compile the entire software I don't know if this change breaks the code.

**Comment by pedromateo** [comment]
Thanks!
Tomorrow early in the morning I'll do these changes (and try to find similar errors) and upload a new version.

**Comment by pedromateo** [comment]
I did this change to make it work:

try {
			a = new File(mybase).getCanonicalFile().toURI().getPath();
			a = a.replace("/", Defines.PATH_SEP);// makes it work in Windows and Linux systems
			b = new File(mypath).getCanonicalFile().toURI().getPath();
			b = b.replace("/", Defines.PATH_SEP);// makes it work in Windows and Linux systems
		} catch (IOException e) {
			e.printStackTrace();
		}

Hope it helps. I will upload the rest of the code.

**Comment by mariolatronico** [comment]
Same error. I suspected it was the same but I wanted to try it.
The problems lies in the line _split()_ function. It's javadoc says : 
```
public String[] split(String regex)

Splits this string around matches of the given regular expression. 
```
and since "\" (the default path separator in Windows and the values of _Defines.PATH_SEP in Windows) is not a valid regular expression, it throws the exception.

I will try to compile the software with Eclipse and see if I can submit a patch.
By the way, do you think that the java project can be "mavenized" to be ide-independent and supplied with unit tests ? I can try to do that if this make sense.

**Comment by pedromateo** [comment]
I added a new version including pattern quote.
Solution based on: http://stackoverflow.com/questions/10336293/splitting-filenames-using-system-file-separator-symbol
Hope it works :-)

**Comment by mariolatronico** [comment]
I just tried on windows, it successfully generate the project.

Thank you.

**Comment by pedromateo** [comment]
Thank you too for your interest and help.
Hope you can use TUG and make profit of it, and do not hesitate for asking for help anytime you want to improve TUG.

**Comment by mariolatronico** [comment]
:) Thank you for open sourcing the software.
